module.exports = {
  Adaptive: 'You can ingest exotic consumables without ill-effect, and use machines, devices, etc. not designed for your species with ease.',
  AI: 'You have a loyal artificial intelligence NPC at your disposal, which you can command to enter, unlock, and activate systems.',
  Animate: 'Using cosmic energy, you assemble inanimate objects into an artificial Crew, which serves you. Its properties depend on the materials used. You may only have one Animated Crew at a time.',
  Assassin: 'When you kill someone with a 6, you can choose to leave no trace of the act.',
  Authority: 'In a position of superiority, you can command any group of NPCs as if they were your loyal troops.',
  Bravery: 'You feel no terror, fear, revulsion, or hopelessness. You, and any Crew you command, are Fearless.',
  Builder: 'With a few hours work, build or modify a structure that is: Defensible, a Shelter, Hidden, or a Workplace.',
  Chemistry: 'Create antidotes, vaccines, drugs, or poisons on a 6. On a 5, it has reduced potency or side effects.',
  Chrome: 'Your cybernetic components protect you like a second skin. Add +1 Strike to Armor in addition to any worn Armor.',
  Collaborator: 'Whenever you gain an Advantage through a special ability, all allies present also gain 1 Advantage.',
  Connected: 'You know the right people to get what you want, you\'re always able to spend credits as a bribe in the legal, political, or faction worlds. Amount determined by the change required.',
  Contacts: 'You have acquaintances all over the galaxy. Whenever you enter a civilized area, name an NPC contact you have in the area.',
  Criminal: 'When you commit a theft, smuggling, extortion, or any similar crime with a 6, you leave behind no evidence to incriminate you.',
  Dismantle: 'When you demolish or break something, roll a Body check, and you can do it: Quickly, Quietly, Recover Materials from it, or Easily Rebuild it. On a 5 choose 1, on a 6, choose 2.',
  Explorer: 'When leading an expedition, make a Mind check. On a 6, you can choose to find something profitable, something useful, or something uniquely awesome. On a 5, the Spacemaster chooses.',
  Fame: 'You are famous, or infamous, throughout the galaxy. Your friends can use your name as well, but you suffer any consequences.',
  Flight: 'Your mastery of cosmic energy allows you to fly.',
  Healer: 'Heal 2 Strikes when using a medpac, instead of 1.',
  Heavy: 'Carry heavy weapons, armor, and twice as much gear with ease, and ignore high gravity.',
  Hijack: 'Any time you successfully access a computer system, you lock out all other users at your discretion.',
  Hydraulic: 'Pistons in your limbs allow your unarmed and melee attacks to ignore Armor.',
  Improvise: 'With some scrap metal and spare parts, you can improvise a simple melee weapon, explosive, or set of tools.',
  Inspiring: 'Choose an emotion and a medium. Roll Spirit to make your audience feel that emotion, on a 6 you also: Gain an Admirer, are Treated Lavishly, or can Command the audience.',
  Interrogate: 'When you interrogate someone at your mercy, gain 3 Advantages, when you act on the information you can cash in the Advantages for a +1d6 on the roll.',
  Investigation: 'When you investigate a scene with a successful Mind check, you gain Advantages. You can cash in the Advantages for a +1d6 on a roll related to the information from the scene. Gain 1 Advantage on a 5 and gain 3 Advantages on a 6.',
  Leadership: 'You have an elite Squad or Team under your Command.',
  Linguist: 'You are reasonably fluent in the languages of all known societies and species, a successful Mind check allows you the same with a newly-encountered or long-dead culture\'s written or spoken language.',
  Luxury: 'All of your clothes and accommodations are High-End, and you gain a Personal Attendant NPC who sees to your needs.',
  Marketing: 'In any civilized area you can always find one of the following markets: HighEnd, Black Market, and Quick Deals.',
  Mediator: 'When you successfully insert yourself into an interpersonal situation, choose 1: each participant gains 1 Advantage over the other, Escalate the situation to either Fight or Flight, or Defuse the situation to prevent violence.',
  Motorized: 'Your speed and reflexes are artificially enhanced, allowing extreme acts of movement, acrobatics, and flexibility.',
  Navigation: 'Whenever you plan a long voyage, you can choose 1, it will be: Fast, Safe, Pleasant, or Profitable.',
  Program: 'When you successfully access a computer system, set up a triggered action the system can perform when the conditions are met.',
  Protection: 'When a nearby victim would suffer harm or consequences, you can impose yourself instead. Roll Spirit: on a 6 they are protected, and you suffer a lesser consequence, on a 5 you suffer instead of them, on a 4 or less, you both suffer.',
  Reckless: 'When you act in a risky way against long-shot odds, roll 1D6. On a 1-3, it goes spectacularly bad, on a 4-6 it goes amazingly well.',
  Researchers: 'You command a team of scientists or technicians, using Mind instead of Spirit.',
  Ritual: 'By performing a complicated ritual of hexes and charms, you can perform any act using the Mind stat instead of its normal stat.',
  Scapegoat: 'When you would suffer legal, social, or financial consequences, name someone else instead. On a 6, they suffer the consequences instead. On a 5, they suffer, but they know what you did. On a 4-, it doesn\'t work, and they know what you did.',
  Scout: 'When you scout out some aspect of the wilderness, gain 3 Advantages, when you act on the information you can cash in the Advantages for a +1d6 on the roll.',
  Sneaky: 'When unobserved, disappear from sight and reappear somewhere else later.',
  Socialized: 'When you evaluate some aspect of society (culture, tradition, politics, government, etc), gain 3 Advantages. When you act on the information, you can cash in the Advantages for a +1d6 on the roll.',
  Surprise: 'When you surprise someone, you can choose to: Kill, Injure, Rob, Disarm, Disable, or Capture them. On a 6, pick one, on a 5 the Spacemaster gives you a choice of 2.',
  Survival: 'In any environment, except the most barren and inhospitable, you can always scavenge: Edible Food and Drink, Basic Medicine or First Aid supplies, and a Primitive Melee Weapon.',
  Tactical: 'On a partial success in combat, you choose the side effects (or cost) instead of the Spacemaster.',
  Toughness: 'Gain an additional +1 Strike.',
  Transformation: 'You transform your physical body into a shape up to 3x bigger or smaller than your standard form. You can transform into a specific individual by successfully studying them with a Mind check, or spending an Advantage you have on them.',
  Tuning: 'Customize and fine-tune a vehicle or computer console. The next time anyone uses it, they gain +1d6 from your Help.',
  Upgraded: 'With a successful Mind check, you temporarily improve a weapon or vehicle by adding one of the following traits: Weapons (Burst, Concealed, Dangerous, Explosive, Impact, Keyed, Ricochet, Penetrating, Rapid Fire, Silenced, Stun, Stylish) or Vehicles (Agile, Armed, Boosters, Containment, Controlled, Keyed, Luxury, Plated, Reinforced, Rugged, Sealed, Stealthy)',
  Visions: 'You meditate and envision a possible situation or scenario. On a successful Mind check, you gain Advantages, which can be used if the situation or scenario occurs. You can cash in the Advantages for a +1d6 on a roll: gain 1 Advantage on a 5 and gain 3 Advantages on a 6.',
  Weightless: 'You are completely at ease in a low-gravity/no gravity environment, and can act freely without penalty.',
  Wired: 'You can mentally connect to any computer system within line of sight without physically accessing it, and remain connected as long as you are in range thereafter.'
}